name: Run Tests
on: push
jobs:
  build:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker build
        run: docker build -t flatpak-external-data-checker .
      - name: run tests
        run: docker run -v $PWD:/opt -w /opt flatpak-external-data-checker python3 -m unittest discover --verbose --buffer
